#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    min1=scores[0]
    max1=scores[0]
    countMin=0
    countMax=0
    for score in scores:
        if min1 < score :
            min1=score
            countMin+=1
        if max1 > score:
            max1=score
            countMax+=1
    return countMin,countMax

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
